applications/lafayette/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
   path('inicio/', views.InicioView.as_view(),name='inicio'),


   path('', views.Index2View,name='index1'),
   path('contacto/', views.ContactoCreateView.as_view(),name='contacto'),
   path('registrar/', views.RegistrarCreateView.as_view(),name='registrar'),

   path('addcliente/', views.ClienteCreateView.as_view(),name='addcliente'),
   path('updatecliente/<pk>/', views.ClienteUpdate.as_view(),name='updatecliente'),
   path('borrarcliente/<pk>/', views.ClienteDeleteView.as_view(),name='borrarcliente'),
   

   path('addprospecto/', views.ProspectoCreateView.as_view(),name='addprospecto'),
   path('updateprospecto/<pk>/', views.ProspectoUpdate.as_view(),name='updateprospecto'),
   path('borrarprospecto/<pk>/', views.ProspectoDeleteView.as_view(),name='borrarprospecto'),


   path('finventa/<pk>/', views.FinVenta,name='finventa'),
   path('tablacliente/', views.listaClientes,name='tablacliente'),
   path('tablaprospecto/', views.listaProspecto,name='tablaprospecto'),

   path('ventacompra/', views.listaVentaCompra,name='ventacompra'),
   path('updateregistrar/<pk>/', views.RegistrarUpdate.as_view(),name='updateregistrar'),
    path('borrarregistro/<pk>/', views.RegistrarDeleteView.as_view(),name='borrarregistro'),

   path('qsomos/',views.Qsomos.as_view(),name='qsomos'),
]

lafayette/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.lafayette.urls')),
    re_path('', include('applications.users.urls')),
]

applications/lafayette/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


Userr = get_user_model()

# Create your models here.
class Operacion(models.Model):
    tipo = models.CharField('Operación a realizar', max_length=20)
    def __str__(self):
        return self.tipo 

class Producto(models.Model):
    producto = models.CharField('Producto a ofertar', max_length=50)
    def __str__(self):
        return self.producto 

class Amigo(models.Model):
    opc = (
        ('Ofrece','Ofrece'),
        ('Desea','Desea'),
    )

    opc2 = (
        ('1','Publica'),
        ('2','Privada'),
    )
    user = models.ForeignKey(Userr, null=True,blank=True, on_delete=models.CASCADE)
    cliente = models.CharField('Nombre Completo del Cliente', max_length=60)
    operacion = models.ForeignKey(Operacion, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    municipio = models.CharField('Municipio', max_length=30)
    estado = models.CharField('Estado', max_length=30)
    email = models.EmailField()
    telefono = models.CharField('Telefono', max_length=10)
    opcion = models.CharField('Operacion a realizar', max_length=20,choices=opc)
    titulo = models.CharField('Título', max_length=300)
    nota = models.CharField('Descripción del inmueble', max_length=300)
    publicar = models.CharField('Esta nota sera ?', max_length=20,choices=opc2)
    img=models.ImageField('Seleccionar una imagen',upload_to = 'static/media',null=True,blank=True)
    precio = models.FloatField('Precio ',max_length=50)
    finalizada = models.BooleanField(default=False) 
    
    def __str__(self):
        return self.cliente 



class Contacto(models.Model):
    opc = (
        ('Vender','Vender'),
        ('Rentar','Rentar'),
    )
    user = models.ForeignKey(Userr, null=True,blank=True, on_delete=models.CASCADE)
    nombre = models.CharField('Nombre del Cliente', max_length=60)
    telefono = models.CharField('Número de teléfono', max_length=10)
    opcion = models.CharField('Vender o Rentar', max_length=20,choices=opc)
    datos = models.CharField('Datos de la propiedad', max_length=600)
    email = models.EmailField('Correo Electronico')

    #ubicacion = models.CharField('Ubicación', max_length=50)
    tipo = models.CharField('Tipo de inmueble', max_length=30)
    municipio = models.CharField('Municipio', max_length=30)
    estado = models.CharField('Estado', max_length=30)
    colonia = models.CharField('Colonia', max_length=30)
    calle = models.CharField('Calle', max_length=100)
    cp = models.CharField('Código postal', max_length=5)
    
    def __str__(self):
        return self.nombre 

class Prospecto(models.Model):

    inte = (
        ('Si','Si'),
        ('No','No'),
    )

    user = models.ForeignKey(Userr, null=True,blank=True, on_delete=models.CASCADE)
    nombre = models.CharField('Nombre del Prospecto', max_length=60)
    telefono = models.CharField('Número de teléfono', max_length=10)
    fechac = models.DateField('Fecha de contacto')
    fechap = models.DateField('Fecha de plática')
    fechai = models.DateField('Fecha de Inscripción',blank=True,null=True)
    interesado = models.CharField('Interesado', max_length=20,choices=inte)
    inscrito = models.CharField('Inscrito', max_length=20,choices=inte)
    contactado = models.CharField('Contactado', max_length=20,choices=inte)

    def __str__(self):
        return self.nombre 

templates/cliente/add_cliente.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 


{% block title %}
    
{% endblock title %}
    
{% block content %}

<div class="d-flex" id="content-wrapper">
    {% include 'header.html' %}
    
    <div class="w-100">
        <div id="content" class="bg-grey w-100">
  
  <div class="container" style="margin-top: 20px;  ">
    <h5>Registro para Referir Clientes</h5>

      <form method="POST" enctype="multipart/form-data" novalidate> 
        {% csrf_token %} 
        <div class="row">
  
          <div class="col">
            {{ form.cliente|as_crispy_field }}
          </div>         
          <div class="col">
            {{ form.operacion|as_crispy_field }}
          </div>         
          
          <div class="col">
            {{ form.producto|as_crispy_field }}
          </div>          
        </div>

        <div class="row">
          <div class="col">
            {{ form.municipio|as_crispy_field }}
          </div>
          <div class="col">
            {{ form.estado|as_crispy_field }}
          </div>         
          <div class="col">
            {{ form.email|as_crispy_field }}
          </div>         
        </div>

        <div class="row">
            <div class="col">
              {{ form.telefono|as_crispy_field }}
            </div>
            <div class="col">
              {{ form.opcion|as_crispy_field }}
            </div>   
            <div class="col">
              {{ form.publicar|as_crispy_field }}
            </div>                 
          </div>

          <div class="row">
            <div class="col">
              {{ form.titulo|as_crispy_field }}
            </div>
            <div class="col">
              {{ form.precio|as_crispy_field }}
            </div>  
            <div class="col">
              {{ form.img|as_crispy_field }}
            </div>         
          </div>

          <div class="row">
            <div class="col">
              {{ form.nota|as_crispy_field }}
            </div>  
            </div>


          <div class="col">
            <button type="submit" class="btn btn-success">Guardar</button>
            <a class="btn btn-secondary" onclick="javascript:history.back();">Cancelar</a>
           </div> 

      </form>

</div>

<script>
  $(document).ready(function(){

    $('#id_opcion').on('change',function(){
        var selectValor = $(this).val();
        //alert (selectValor);

        if (selectValor == 'Desea') {
          $('#div_id_img').hide();

        } else {
            $('#div_id_img').show();
        }
    });


  });
  </script>  


{% endblock content %}

templates/cliente/borrar_referido.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 


{% block title %}
    Socios
{% endblock title %}


{% block content %}

<div class="d-flex" id="content-wrapper">
  {% include 'header.html' %}
  <div class="w-100">
      <div id="content" class="bg-grey w-100">
        <div class="container" style="margin-top: 50px;  ">

    <h5 >Desea Eliminar el Cliente Referido... !!</h5>

    <div class="row">

        <form  method="POST"> {% csrf_token %}
            <div class="form-row ">

                <div class="col-5"> 
                    <button type="submit" class="btn text-white  bg-success">Confirmar...</button>
                    </div>
                </div>

        </form>
    </div>
</div>
</div>
</div>
</div>


{% endblock content %}

templates/cliente/borrar_registro.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 


{% block title %}
    Socios
{% endblock title %}


{% block content %}

<div class="d-flex" id="content-wrapper">
  {% include 'header.html' %}
  <div class="w-100">
      <div id="content" class="bg-grey w-100">
        <div class="container" style="margin-top: 50px;  ">

    <h5 >Desea eliminar la propiedad registrada... !!</h5>

    <div class="row">

        <form  method="POST"> {% csrf_token %}
            <div class="form-row ">

                <div class="col-5"> 
                    <button type="submit" class="btn text-white  bg-success">Confirmar...</button>
                    </div>
                </div>

        </form>
    </div>
</div>
</div>
</div>
</div>


{% endblock content %}

templates/cliente/fin_venta.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 


{% block title %}
    
{% endblock title %}
    
{% block content %}

<div class="d-flex" id="content-wrapper">
    {% include 'header.html' %}
    
    <div class="w-100">
        <div id="content" class="bg-grey w-100">
  
  <div class="container" style="margin-top: 20px;  ">

        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-8">
                  <h2 class="font-weight-bold mb-0">{{alumnos.cliente}}</h2>
                  <h5 class="font-weight-bold mb-0">{{alumnos.titulo}}</h5>
                  <p class="lead text-muted">Finalizar la venta del inmueble</p>
                  {% for message in messages %}
                  <div class="alert alert-success" role="alert">
                  <h5 class="font-weight-bold mb-0">{{message}}</h5>
                    </div>
                  {% endfor %}
                </div>
                <div class="col-lg-3 col-md-4 d-flex">
                
                    <form method="POST" novalidate>  {% csrf_token %} 
                        <input type="hidden" value="{{alumnos.precio }}" name="valor" >
                  <button type="submit" class="btn btn-primary w-100 align-self-center">Finalizar Venta</button>
                   </form>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="card rounded-0">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 d-flex stat my-3">
                            <div class="mx-auto">
                                <h6 class="text-muted">Precio</h6>
                                <h3 class="font-weight-bold">{{alumnos.precio}}</h3>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 d-flex stat my-3">
                            <div class="mx-auto">
                                <h6 class="text-muted">Lugar</h6>
                                <h4 class="font-weight-bold">{{alumnos.municipio}}, {{alumnos.estado}}</h4>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 d-flex my-3">
                            <div class="mx-auto">
                                <h6 class="text-muted">Teléfono</h6>
                                <h4 class="font-weight-bold">{{alumnos.telefono}}</h4>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 d-flex my-3">
                            <div class="mx-auto">
                                <h6 class="text-muted">Venta Finalizada</h6>
                                <h3 class="font-weight-bold">
                                    {% if alumnos.finalizada  %}
                                     Si
                                    {% else %}  
                                     No
                                    {% endif %}

                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">

            <div class="card rounded-0">
                <div class="card-body">
                    <div class="row">
                        <h5 > {{alumnos.nota}} </h5>

                        <img  src="/{{ alumnos.img }}">
                    </div>
                </div>
            </div>       
     </div>
    </div>
  </div>
 </div>



{% endblock content %}

templates/cliente/registrar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 


{% block title %}
    Socios
{% endblock title %}


{% block content %}

<div class="d-flex" id="content-wrapper">
  {% include 'header.html' %}
  
  <div class="w-100">
      <div id="content" class="bg-grey w-100">

<div class="container" style="margin-top: 20px;  ">
    <h2>Bienvenido a lafayette</h2>
    <p>Amigos de lafayette Inmobiliaria. <b> Quiero me ayuden a vender/rentar mi propiedad </b> </p>

    <form method="POST" enctype="multipart/form-data" novalidate> 
        {% csrf_token %} 
        <div class="row">
  
          <div class="col">
            {{ form.nombre|as_crispy_field }}
          </div>         
          <div class="col">
            {{ form.telefono|as_crispy_field }}
          </div>         
          
          <div class="col">
            {{ form.opcion|as_crispy_field }}
          </div>  

        </div>

        <div class="row">
          <div class="col">
            {{ form.email|as_crispy_field }}
          </div>   
            <div class="col">
                {{ form.datos|as_crispy_field }}
            </div>  
            <div class="col">
              {{ form.cp|as_crispy_field }}
          </div>       
        </div>

        <div class="row">
          <div class="col">
            {{ form.tipo|as_crispy_field }}
          </div>   
            <div class="col">
                {{ form.calle|as_crispy_field }}
            </div>  
            <div class="col">
              {{ form.colonia|as_crispy_field }}
          </div>       
        </div>

        <div class="row">
          <div class="col">
            {{ form.municipio|as_crispy_field }}
          </div>   
            <div class="col">
                {{ form.estado|as_crispy_field }}
            </div>  
        </div>


          <div class="col">
            <button type="submit" class="btn btn-success">Guardar</button>
           </div> 

      </form>

    </div>
  </div>
  </div>

</div>


{% endblock content %}

templates/cliente/tabla_clientes.html
{% extends 'base.html' %}
{% block content %}


<div class="d-flex" id="content-wrapper">
    {% include 'header.html' %}
    
    <div class="w-100">
        <div id="content" class="bg-grey w-100">

<div class="container" style="margin-top: 50px;  ">
    <h5>Clientes Referidos</h5>

    <div class="row"   >
        <a  href=" {% url 'app:addcliente' %}" class="btn text-white  bg-success">Referir Cliente</a>
    </div>
    <div class="row">
            <table class="table table-sm  table-hover ">
            <thead class="text-white bg-secondary">
                <tr>
                <th>Socio</th>   
                <th>Cliente</th>
                <th>Operacion</th>
                <th>Producto</th>
                <th>Municipio</th>
                <th>Estado</th>
                <th>Telefono</th>
                <th>Acción</th>
                <th width="20" >Editar</th>
                <th width="20" >Mas</th>
                <th width="20" >Borrar</th>
                </tr>
            </thead>
            <tbody>

                {% for e in users  %}
                <tr>
                <td>{{e.user}} </td>
                <td>{{e.cliente}} </td>
                <td>{{e.operacion}} </td>
                <td>{{e.producto}} </td>
                <td>{{e.municipio}} </td>
                <td>{{e.estado}} </td>
                <td>{{e.telefono}} </td>
                <td>{{e.opcion}} </td>
                {% if not e.is_staff  %}
                <td width="20"><a class="btn btn-sm btn-info" href=" {% url 'app:updatecliente' e.id  %} "><i class="icon ion-md-brush mr-0"></i></a></td>
                {% endif   %}
                <td width="20"><a class="btn btn-sm btn-warning" href=" {% url 'app:finventa' e.id  %} "><i class="icon ion-ios-browsers mr-0"></i></a></td>
                <td width="20" align="center"><a class="btn btn-sm btn-danger" href=" {% url 'app:borrarcliente' e.id  %} "><i class="icon ion-md-trash mr-0"></i></a></td>

            </tr>
                {% endfor %}

            </tbody>
            </table>
    </div>

<div class="row" >

    {% if users.has_other_pages %}
           
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            
            {% if users.has_previous %}
            <li class="page-item ">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}" >Atras</a>
            </li>
            {% endif %}
                
                {% for i in users.paginator.page_range  %}               
                {% if users.number == i %}
                <li class="page-item"><a class="page-link">{{i}}</a> </li>
                 {% else %} 
                 <li class="page-item"><a class="page-link" href="?page={{i}}" >{{i}}</a></li>
                {% endif %}
                {% endfor %}
                
          {% if users.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{users.next_page_number}}" >Siguiente</a>
         </li>
         {% endif %}

        </ul>
      </nav>

      {% endif %}


</div>

</div>
</div>
</div>


</div>



{% endblock content %}