applications/lafayette/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
   path('inicio/', views.InicioView.as_view(),name='inicio'),


   path('', views.Index2View,name='index1'),
   path('contacto/', views.ContactoCreateView.as_view(),name='contacto'),
   path('registrar/', views.RegistrarCreateView.as_view(),name='registrar'),

   path('addcliente/', views.ClienteCreateView.as_view(),name='addcliente'),
   path('updatecliente/<pk>/', views.ClienteUpdate.as_view(),name='updatecliente'),
   path('borrarcliente/<pk>/', views.ClienteDeleteView.as_view(),name='borrarcliente'),
   

   path('addprospecto/', views.ProspectoCreateView.as_view(),name='addprospecto'),
   path('updateprospecto/<pk>/', views.ProspectoUpdate.as_view(),name='updateprospecto'),
   path('borrarprospecto/<pk>/', views.ProspectoDeleteView.as_view(),name='borrarprospecto'),


   path('finventa/<pk>/', views.FinVenta,name='finventa'),
   path('tablacliente/', views.listaClientes,name='tablacliente'),
   path('tablaprospecto/', views.listaProspecto,name='tablaprospecto'),

   path('ventacompra/', views.listaVentaCompra,name='ventacompra'),
   path('updateregistrar/<pk>/', views.RegistrarUpdate.as_view(),name='updateregistrar'),
    path('borrarregistro/<pk>/', views.RegistrarDeleteView.as_view(),name='borrarregistro'),

   path('qsomos/',views.Qsomos.as_view(),name='qsomos'),
]

lafayette/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.lafayette.urls')),
    re_path('', include('applications.users.urls')),
]

templates/ventas/tabla_vender.html
{% extends 'base.html' %}
{% block content %}


<div class="d-flex" id="content-wrapper">
    {% include 'header.html' %}
    
    <div class="w-100">
        <div id="content" class="bg-grey w-100">

<div class="container" style="margin-top: 50px;  ">
    <h5>Propiedades Registradas </h5>

    <div class="row"   >
        <a  href=" {% url 'app:registrar' %}" class="btn text-white  bg-success">Vender o Comprar</a>
    </div>
    <div class="row">
            <table class="table table-sm  table-hover ">
            <thead class="text-white bg-secondary">
                <tr>
                 {% if user.is_staff %}   
                <th>Usuario</th>   
                 {% endif %}   
                <th>Nombre</th>   
                <th>Teléfono</th>
                <th>Correo</th>
                <th>Acción</th>
                <th>Descripción</th>                
                <th width="20">Editar</th>
                <th width="20">Eliminar</th>
                </tr>
            </thead>
            <tbody>

                {% for e in users  %}
                <tr>
                {% if user.is_staff %}   
                <td>{{e.user}} </td>
                {% endif %}    
                <td>{{e.nombre}} </td>
                <td>{{e.telefono}} </td>
                <td>{{e.email}} </td>
                <td>{{e.opcion}} </td>
                <td>{{e.datos}} </td>
                <td width="20" align="center"><a class="btn btn-sm btn-info " href=" {% url 'app:updateregistrar' e.id  %} "><i class="icon ion-md-brush mr-0"></i></a></td>
                <td width="20" align="center"><a class="btn btn-sm btn-danger" href=" {% url 'app:borrarregistro' e.id  %} "><i class="icon ion-md-trash mr-0"></i></a></td>
            </tr>
                {% endfor %}

            </tbody>
            </table>
    </div>

<div class="row" >

    {% if users.has_other_pages %}
           
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            
            {% if users.has_previous %}
            <li class="page-item ">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}" >Atras</a>
            </li>
            {% endif %}
                
                {% for i in users.paginator.page_range  %}               
                {% if users.number == i %}
                <li class="page-item"><a class="page-link">{{i}}</a> </li>
                 {% else %} 
                 <li class="page-item"><a class="page-link" href="?page={{i}}" >{{i}}</a></li>
                {% endif %}
                {% endfor %}
                
          {% if users.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{users.next_page_number}}" >Siguiente</a>
         </li>
         {% endif %}

        </ul>
      </nav>

      {% endif %}


</div>

</div>
</div>
</div>


</div>



{% endblock content %}

templates/ventas/vender.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 

{% load static %}

{% block title %}
lafayette
{% endblock title %}


{% block content %}

{% include 'nav.html' %}

        <section class=" py-1">
        <div class="container">
        <div class="mu-header-featured-area" style="margin-top: 0px;">

            <div class="mu-header-featured-content">
                <h2>Bienvenido a lafayette</h2>
                <p>Amigos de lafayette Inmobiliaria. Quiero me ayuden a vender/rentar mi propiedad. Les dejo mis datos para contactarme  </p>
           


                <form method="POST" enctype="multipart/form-data" novalidate> 
                    {% csrf_token %} 
                    <div class="row">
              
                      <div class="col">
                        {{ form.nombre|as_crispy_field }}
                      </div>         
                      <div class="col">
                        {{ form.telefono|as_crispy_field }}
                      </div>         
                      
                      <div class="col">
                        {{ form.opcion|as_crispy_field }}
                      </div>  
        
                    </div>
        
                    <div class="row">
                      <div class="col">
                        {{ form.email|as_crispy_field }}
                      </div>   
                        <div class="col">
                            {{ form.datos|as_crispy_field }}
                        </div>  
                        <div class="col">
                          {{ form.cp|as_crispy_field }}
                      </div>       
                    </div>
            
                    <div class="row">
                      <div class="col">
                        {{ form.tipo|as_crispy_field }}
                      </div>   
                        <div class="col">
                            {{ form.calle|as_crispy_field }}
                        </div>  
                        <div class="col">
                          {{ form.colonia|as_crispy_field }}
                      </div>       
                    </div>
            
                    <div class="row">
                      <div class="col">
                        {{ form.municipio|as_crispy_field }}
                      </div>   
                        <div class="col">
                            {{ form.estado|as_crispy_field }}
                        </div>  
                    </div>

                      <div class="col">
                        <button type="submit" class="btn btn-success">Enviar</button>
                       </div> 
            
                  </form>



                </div>
            </div>
        </div >
    </section> 

{% endblock content %}