applications/lafayette/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
   path('inicio/', views.InicioView.as_view(),name='inicio'),


   path('', views.Index2View,name='index1'),
   path('contacto/', views.ContactoCreateView.as_view(),name='contacto'),
   path('registrar/', views.RegistrarCreateView.as_view(),name='registrar'),

   path('addcliente/', views.ClienteCreateView.as_view(),name='addcliente'),
   path('updatecliente/<pk>/', views.ClienteUpdate.as_view(),name='updatecliente'),
   path('borrarcliente/<pk>/', views.ClienteDeleteView.as_view(),name='borrarcliente'),
   

   path('addprospecto/', views.ProspectoCreateView.as_view(),name='addprospecto'),
   path('updateprospecto/<pk>/', views.ProspectoUpdate.as_view(),name='updateprospecto'),
   path('borrarprospecto/<pk>/', views.ProspectoDeleteView.as_view(),name='borrarprospecto'),


   path('finventa/<pk>/', views.FinVenta,name='finventa'),
   path('tablacliente/', views.listaClientes,name='tablacliente'),
   path('tablaprospecto/', views.listaProspecto,name='tablaprospecto'),

   path('ventacompra/', views.listaVentaCompra,name='ventacompra'),
   path('updateregistrar/<pk>/', views.RegistrarUpdate.as_view(),name='updateregistrar'),
    path('borrarregistro/<pk>/', views.RegistrarDeleteView.as_view(),name='borrarregistro'),

   path('qsomos/',views.Qsomos.as_view(),name='qsomos'),
]

applications/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login_app'
#user_app:user-logout

urlpatterns = [
    #path('', views.LoginUser.as_view(),name='login'),
    path('addusuario/', views.RegistroUserView.as_view(), name='addusuario'),
    path('login/', views.LoginUser.as_view(), name='user-login'),
    path('logout/', views.SalirView.as_view(), name='user-logout'),
    path('update/<pk>/', views.UserUpdate.as_view(), name='user-update'),

    path('listuser/', views.listaUsuarios, name='listuser'),
    path('borraruser/<pk>/', views.UserDeleteView.as_view(),name='borraruser'),

] 

lafayette/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.lafayette.urls')),
    re_path('', include('applications.users.urls')),
]

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'jquery/jquery.min.js'  %}"></script>
    <script type="text/javascript" src="{% static 'jquery/jquery.js'  %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js'  %}"></script>


    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Muli:300,700&display=swap" rel="stylesheet">
    <!-- Ionic icons -->
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <title> 
    {% block title %}
        Lafayette
    {% endblock title %}
   </title>

   <script type="text/javascript">

        var user = '{{ request.user }}' 

   </script>

</head>
<body  style=" background-color: #eee; background: linear-gradient(to top, #fff 10%, rgba(93, 42, 141, 0.4) 90%) no-repeat">
    


    {% block content %}
        
    {% endblock content %}

    <script type="text/javascript" src=" {% static 'js/bootstrap.min.js' %}  "> </script>
    <script type="text/javascript" src=" {% static 'js/bootstrap.js' %}  "> </script>
    <script type="text/javascript" src=" {% static 'jquery/jquery.js' %}  "> </script>


    
</body>
</html>

templates/base2.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    
    <title> 
    {% block title %}
        
    {% endblock title %}
   </title>
</head>
<body>
    


    {% block content %}
        
    {% endblock content %}

 
    <script src=" {% static 'js/bootstrap.min.js' %}  "> </script>
    <script src=" {% static 'js/bootstrap.js' %}  "> </script>
    <script src=" {% static 'jquery/jquery.js' %}  "> </script>
    <script src=" {% static 'jquery/jquery.min.js' %}  "> </script>
        


    <script>
        $(document).ready(function(){
            $('.message a').click(function(){
            $('form').animate({height: "toggle", opacity: "toggle"}, "slow");
            });
        });    
    </script>

</body>
</html>

templates/header.html
{% load static %}

<div id="sidebar-container" class="bg-primary">
    <div class="logo">
        <h4 class="text-light font-weight-bold mb-0">Lafayette</h4>
    </div>
    <div class="menu">
        <a href="{% url 'app:inicio' %}" class="d-block text-light p-3 border-0"><i class="icon ion-md-apps lead mr-2"></i>
            Inicio</a>

        <a href="{% url 'login_app:listuser' %}" class="d-block text-light p-3 border-0"><i class="icon ion-md-people lead mr-2"></i>
            Socios Registrados</a>


        <a href="{% url 'app:tablacliente' %}" class="d-block text-light p-3 border-0"><i class="icon ion-ios-appstore lead mr-2"></i>
            Cliente Referidos</a>

        <a href="{% url 'app:tablaprospecto' %}" class="d-block text-light p-3 border-0"><i class="icon ion-ios-appstore lead mr-2"></i>
                Prospectos</a>

        <a href="{% url 'app:ventacompra' %}" class="d-block text-light p-3 border-0"><i class="icon ion-md-stats lead mr-2"></i>
            Registrar propiedades</a>
  

        <a href="{% url 'login_app:user-logout' %}"  class="d-block text-light p-3 border-0"><i class="icon ion-md-person lead mr-2"></i>
            Salir</a>

    </div>
</div>

templates/index.html
{% extends 'base2.html' %}
{% load static %}


{% block title %}
    Lafayette
{% endblock title %}


{% block content %}

<div class="container" style="margin-top: 30px;">

    <div class="wrapper bg-white">
        <div class="h2 text-center">Lafayette</div>
        <div class="h4 text-muted text-center pt-2"> Ingrese sus datos de acceso </div>
        <form class="pt-3" action="" method="post">{% csrf_token %}
            <div class="form-group py-2">
                {{ form.username }}
            </div>
            <div class="form-group py-1 pb-2">
                {{ form.password }}
            </div>
            <div align="center">
                <img  src="{% static 'img/logo.jpg' %}" alt="" height="100px" >
            </div>

            <div class="d-flex align-items-start">
            </div> <button class="btn btn-block text-center my-3">Iniciar sesión</button>
            {% for message in messages %}
            <p>{{message}}</p>
            {% endfor %}
        </form>
    </div>


</div>

{% endblock content %}

templates/index1.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
lafayette
{% endblock title %}


{% block content %}


{% include 'nav.html' %}

    <div id="content" class=" w-100">
        <div class="container">
            <div class="row" >

            <div class="mu-header-featured-content  ">
                <h3 class="text-white">Bienvenido a <span>lafayette</span></h3>
                <h6 style="margin: 0%;">GANA DINERO EXTRA CON NUESTRO MLM, LAFAYETTE INMOBILIARIA </h6>
                <h6 style="margin: 0%;">Lafayette Inmobiliaria Calle 27 de Febrero H. Cárdenas, Tab.Col. Pueblo Nuevo. 86500</h6>
                <h6 >Teléfonos: 9931820190, Email: lafayetterealstate@gmail.com    </h6>
                </div>


              <div class="card-group"  >
                {% for e in users  %}
                <div class="card"  > 
                  {% if e.img %}
                  <img class="card-img-top" src="/{{ e.img }}"  >
                  {% endif %}
                  <div class="card-body">
                    <h5 class="card-title"> <b>{{e.titulo}} </b></h5>
                    <p>Tel : {{e.telefono}} </p>
                    <p class="card-text">{{e.nota}}.</p>
                </div>
                    <div class="card-footer">
                        <small class="text-muted">{{e.municipio}}, {{e.estado}} </small>
                    </div>
                </div>
                {% endfor %}
              </div>
            </div>
            
    <div class="row" >
        {% if users.has_other_pages %}
               
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                
                {% if users.has_previous %}
                <li class="page-item ">
                    <a class="page-link" href="?page={{page_obj.previous_page_number}}" >Atras</a>
                </li>
                {% endif %}
                    
                    {% for i in users.paginator.page_range  %}               
                    {% if users.number == i %}
                    <li class="page-item"><a class="page-link">{{i}}</a> </li>
                     {% else %} 
                     <li class="page-item"><a class="page-link" href="?page={{i}}" >{{i}}</a></li>
                    {% endif %}
                    {% endfor %}
                    
              {% if users.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{users.next_page_number}}" >Siguiente</a>
             </li>
             {% endif %}
    
            </ul>
          </nav>
    
          {% endif %}

    </div>
</div>
</div>

{% endblock content %}

templates/inicio.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Bienvenido
{% endblock title %}


{% block content %}

<div class="d-flex" id="content-wrapper">
{% include 'header.html' %}

<div class="w-100">
    <div id="content" class="bg-grey w-100">

        <section class="bg-light py-3">
        <div class="container">
        <div class="mu-header-featured-area" style="margin-top: 30px;">
            <div class="mu-header-featured-img" >
            </div>

            <div class="mu-header-featured-content">
                <h1>Bienvenido <span>{{user}}</span></h1>
                <p>GANA DINERO EXTRA CON NUESTRO MLM</p>

                <div class="mu-app-download-area">
                    <h4>UNETE A NUESTRO EQUIPO DE NETWORKMARKETING FORMA PARTE DE</h4>
                    <p>LAFAYETTE INMOBILIARIA Y GANA INGRESOS EXTRAS..</p>
                    <img  src="{% static 'img/logo.jpg' %}" alt=""  >

                </div>

                </div>
            </div>
        </div >
    </section> 
    </div>
</div>
</div>
{% endblock content %}

templates/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-dark border-bottom ">

    <div class="container">
        <ul class="nav justify-content-end">
          <li class="nav-item">

          <a style="margin:0%;padding: 0%;" href=" {% url 'app:index1' %} "> <img  src="{% static 'img/logo.png' %}" height="55px" alt="">    
          </li>

            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'app:index1' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'app:contacto' %}">Quieres vender o rentar una propiedad</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'app:qsomos' %}">Quienes somos?</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'login_app:user-login' %}">Iniciar sesión</a>
              </li>
          </ul>
</div>
</nav>

templates/qsomos.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
lafayette
{% endblock title %}


{% block content %}


{% include 'nav.html' %}

    <div id="content" class="bg-white w-100">
        <div class="container">
            <div class="row" >

            <div class="mu-header-featured-content">
                <h3>Bienvenido a <span>lafayette</span></h3>
                <img  src="{% static 'img/logo.jpg' %}" alt="">

                <h6 style="margin: 0%;">GANA DINERO EXTRA CON NUESTRO MLM, LAFAYETTE INMOBILIARIA </h6>
                <h6 style="margin: 0%;">UNETE A NUESTRO EQUIPO DE NETWORKMARKETING FORMA PARTE DE LAFAYETTE INMOBILIARIA Y GANA INGRESOS EXTRAS.. </h6>
                <p style="margin: 0%;">Lafayette Inmobiliaria Calle 27 de Febrero H. Cárdenas, Tab.Col. Pueblo Nuevo. 86500</p>
                <p >Teléfonos: 9931820190, Email: lafayetterealstate@gmail.com    </p>
                </div>

                <img  src="{% static 'img/lupa.jpg' %}" alt="">


                <P>Utilizamos este medio para publicar terrenos, casas, autos, bodegas, edificios, ranchos, locales, animales, motos, maquinaria pesada, etc. Todo lo que este a la venta o renta ... contactanos y nosotros publicaremos tus fotos y lo mejor estamos iniciando relaciones con empresas interesadas en tu propuestas para una rápida y segura negociación.</P>
<H2>Quienes Somos?</H2>
<P>Lafayette Inmobiliaria es una empresa interactiva, en donde podemos ofrecer tus bienes muebles e inmuebles llegando a todos los niveles sociales de nuestro estado y país.

    Estamos comprometidos con usted, para llegar al cliente final que tenga las 3 "D" deseo, decisión y dinero, para llegar a un acuerdo real y palpable para ambas partes.
    
    Para nosotros es muy importante el anuncio de su bien mueble o inmueble, ya que nos ayuda a captar una cantidad mayor de ofertas y así reducir el tiempo para la adquisición de este mismo, esto es por que somos la Única Guía Inmobiliaria que le  ofrece la oportunidad  a los clientes de obtener ventajas directas y al momento de publicarse en nuestra pagina ,Lafayette Inmobiliaria.</P>

<H2>MISION</H2>
<p>
    Ser el medio de mayor comercialización, local, nacional e Internacional en Proyectos Inmobiliarios, Buscando el mas alto grado de Satisfacción en las necesidades de nuestros clientes, utilizando nuevas tecnologías y medios directos e indirectos para llegar al cliente final y así tener resultados económicos positivos para nuestros clientes y proveedores, la estrategia es GANAR-GANAR..
</p>
           
<h2>VISION</h2>  
<p>
    Ser la guía de referencia en ofertas para comprar, vender o rentar Bienes muebles e Inmuebles en el estado de Tabasco y de México entero, ofreciendo bienes de calidad a todos nuestros clientes.

Haciendo Promociones directas para exceder todas las expectativas de nuestros clientes.
</p>

</div>

</div>
</div>

{% endblock content %}