applications/lafayette/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
   path('inicio/', views.InicioView.as_view(),name='inicio'),


   path('', views.Index2View,name='index1'),
   path('contacto/', views.ContactoCreateView.as_view(),name='contacto'),
   path('registrar/', views.RegistrarCreateView.as_view(),name='registrar'),

   path('addcliente/', views.ClienteCreateView.as_view(),name='addcliente'),
   path('updatecliente/<pk>/', views.ClienteUpdate.as_view(),name='updatecliente'),
   path('borrarcliente/<pk>/', views.ClienteDeleteView.as_view(),name='borrarcliente'),
   

   path('addprospecto/', views.ProspectoCreateView.as_view(),name='addprospecto'),
   path('updateprospecto/<pk>/', views.ProspectoUpdate.as_view(),name='updateprospecto'),
   path('borrarprospecto/<pk>/', views.ProspectoDeleteView.as_view(),name='borrarprospecto'),


   path('finventa/<pk>/', views.FinVenta,name='finventa'),
   path('tablacliente/', views.listaClientes,name='tablacliente'),
   path('tablaprospecto/', views.listaProspecto,name='tablaprospecto'),

   path('ventacompra/', views.listaVentaCompra,name='ventacompra'),
   path('updateregistrar/<pk>/', views.RegistrarUpdate.as_view(),name='updateregistrar'),
    path('borrarregistro/<pk>/', views.RegistrarDeleteView.as_view(),name='borrarregistro'),

   path('qsomos/',views.Qsomos.as_view(),name='qsomos'),
]

lafayette/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.lafayette.urls')),
    re_path('', include('applications.users.urls')),
]

templates/prospecto/add_prospecto.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 


{% block title %}
    
{% endblock title %}
    
{% block content %}

<div class="d-flex" id="content-wrapper">
    {% include 'header.html' %}
    
    <div class="w-100">
        <div id="content" class="bg-grey w-100">
  
  <div class="container" style="margin-top: 20px;  ">
    <h5>Agregar un Prospecto</h5>

      <form method="POST" enctype="multipart/form-data" novalidate> 
        {% csrf_token %} 
        <div class="row">
  
          <div class="col">
            {{ form.nombre|as_crispy_field }}
          </div>         
          <div class="col">
            {{ form.telefono|as_crispy_field }}
          </div>         
          
          <div class="col">
            {{ form.interesado|as_crispy_field }}
          </div>          
        </div>

        <div class="row">
          <div class="col">
            {{ form.fechac|as_crispy_field }}
          </div>
          <div class="col">
            {{ form.fechap|as_crispy_field }}
          </div>         
          <div class="col">
            {{ form.fechai|as_crispy_field }}
          </div>         
        </div>

        <div class="row">
            <div class="col">
              {{ form.inscrito|as_crispy_field }}
            </div>     
            <div class="col">
              {{ form.contactado|as_crispy_field }}
            </div>           
        </div>

          <div class="col">
            <button type="submit" class="btn btn-success">Guardar</button>
            <a class="btn btn-secondary" onclick="javascript:history.back();">Cancelar</a>
           </div> 

      </form>

</div>

{% endblock content %}

templates/prospecto/borrar_prospecto.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 


{% block title %}
    Socios
{% endblock title %}


{% block content %}

<div class="d-flex" id="content-wrapper">
  {% include 'header.html' %}
  <div class="w-100">
      <div id="content" class="bg-grey w-100">
        <div class="container" style="margin-top: 50px;  ">

    <h5 >Desea Eliminar el Prospecto... !!</h5>

    <div class="row">

        <form  method="POST"> {% csrf_token %}
            <div class="form-row ">

                <div class="col-5"> 
                    <button type="submit" class="btn text-white  bg-success">Confirmar...</button>
                    </div>
                </div>

        </form>
    </div>
</div>
</div>
</div>
</div>


{% endblock content %}

templates/prospecto/tabla_prospecto.html
{% extends 'base.html' %}
{% block content %}


<div class="d-flex" id="content-wrapper">
    {% include 'header.html' %}
    
    <div class="w-100">
        <div id="content" class="bg-grey w-100">

<div class="container" style="margin-top: 50px;  ">
    <h5>Lista de Prospecto</h5>

    <div class="row"   >
        <a  href=" {% url 'app:addprospecto' %}" class="btn text-white  bg-success">Nuevo Prospecto</a>
    </div>
    <div class="row">
            <table class="table table-sm  table-hover ">
            <thead class="text-white bg-secondary">
                <tr>
                <th>Nombre</th>
                <th>Teléfono</th>
                <th>Contactado</th>
                <th>Interesado</th>
                <th>Inscrito</th>
                <th>Fecha Contacto</th>
                <th>Fecha Plática</th>
                <th>Fecha Inscripción</th>
                <th width="20" >Editar</th>
                <th width="20" >Borrar</th>
                </tr>
            </thead>
            <tbody>

                {% for e in users  %}
                <tr>
                <td>{{e.nombre}} </td>
                <td>{{e.telefono}} </td>
                <td>{{e.contactado}} </td>
                <td>{{e.interesado}} </td>
                <td>{{e.inscrito}} </td>
                <td>{{e.fechac}} </td>
                <td>{{e.fechap}} </td>
                <td>{{e.fechai}} </td>
                <td width="20"><a class="btn btn-sm btn-info" href=" {% url 'app:updateprospecto' e.id  %} "><i class="icon ion-md-brush mr-0"></i></a></td>
                <td width="20" align="center"><a class="btn btn-sm btn-danger" href=" {% url 'app:borrarprospecto' e.id  %} "><i class="icon ion-md-trash mr-0"></i></a></td>

            </tr>
                {% endfor %}

            </tbody>
            </table>
    </div>

<div class="row" >

    {% if users.has_other_pages %}
           
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            
            {% if users.has_previous %}
            <li class="page-item ">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}" >Atras</a>
            </li>
            {% endif %}
                
                {% for i in users.paginator.page_range  %}               
                {% if users.number == i %}
                <li class="page-item"><a class="page-link">{{i}}</a> </li>
                 {% else %} 
                 <li class="page-item"><a class="page-link" href="?page={{i}}" >{{i}}</a></li>
                {% endif %}
                {% endfor %}
                
          {% if users.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{users.next_page_number}}" >Siguiente</a>
         </li>
         {% endif %}

        </ul>
      </nav>

      {% endif %}


</div>

</div>
</div>
</div>


</div>



{% endblock content %}